### ISSUE TITLE
Deployment to PyPI

### ISSUE THREAD

**Issue by gordthompson** [pauldex/sqlalchemy-firebird#23]
Hi Paul. If you've been working with this dialect for a while and are fairly confident that it is stable enough for public release then it would be a good idea to get this up on [PyPI](https://pypi.org/). In the reasonably near future SQLAlchemy will start warning users of the old internal Firebird dialect that it is deprecated and it would be nice to be able to let them know that they can `pip install sqlalchemy-firebird`.

In a related note, I've been working with @zzzeek and the rest of the SQLAlchemy team on [this issue](https://github.com/sqlalchemy/sqlalchemy/issues/5278) that should help ease the transition. If the change is accepted then we should enable the `firebird://` URI prefix for this dialect before public release. (We can continue to support `firebird2://` to avoid unnecessary headaches for you or anybody else who's been working with this.)

I'd be happy to help out if you would like to proceed. Just let me know.

**Comment by pauldex** [comment]
I would definitely appreciate your help in publishing this project on PyPi.  Give me a a week or so.

I'll ping you when I'm ready to go.  Thanks.

**Comment by pauldex** [comment]
As a side note:  I'm ready to drop the firebird2:// URI myself - it wouldn't cause any headaches.

**Comment by gordthompson** [comment]
> 
> 
> I would definitely appreciate your help in publishing this project on PyPi. Give me a a week or so.
> 
> I'll ping you when I'm ready to go. Thanks.

Okay, great. The process should be almost identical to what I needed to do for sqlalchemy-access, and it was surprisingly easy.

**Comment by gordthompson** [comment]
I just did a test deployment to test.pypi.org and it seems to be working okay. 

```
pip install -i https://test.pypi.org/simple/ sqlalchemy-firebird==0.0.1a1
```

gave me sqlalchemy-firebird, but I had to install the prerequisites (SQLAlchemy and fdb) from pypi.org  first because they aren't available from test.pypi.org.
