### ISSUE TITLE
Tip: Confirm that this dialect is being used in SQLAlchemy 1.3.17+

### ISSUE THREAD

**Issue by gordthompson** [pauldex/sqlalchemy-firebird#26]
SQLAlchemy 1.3.17 added the hook to load this dialect if it is installed, otherwise fall back to the internal dialect. An easy way to confirm which dialect is actually being used is to execute

```python
print(engine.dialect.get_table_names(engine.connect()))
```

This dialect will correctly return the table names, trimmed and case-normalized:

```
['table1', ...
```

while the internal dialect will return the raw table names from rdb$relations:

```
['TABLE1                         ', ...
```

**Comment by fdcastel** [comment]
Can we close this issue?
