### ISSUE TITLE
is_disconnect() doesn't trigger when using FDB

### ISSUE THREAD

**Issue by PracticallyNothing** [pauldex/sqlalchemy-firebird#38]
**The bug**
Using FDB, when a connection is manually removed from the `MON$ATTACHMENTS` table and the dialect gets a "connection shutdown" exception, it doesn't get detected by `is_disconnect()`, because the `if isinstance(e, (...))` check fails, and the connection doesn't get recycled.

**To Reproduce**
1. Connect to a Firebird database with SQLAlchemy and execute a query.
2. Remove the connection from the `MON$ATTACHMENTS` system table.
3. Execute 2 more queries with the same engine.

**Expected behavior**
The first query in step 3 fails, but the connection is recycled and so the second query succeeds.

**Actual behaviour**
The connection is not recycled and both queries fail to execute.

**Comment by pauldex** [comment]
Please let me know if this still happens with the latest version of sqlalchemy-firebird

**Comment by PracticallyNothing** [comment]
Hi, apologies for the very late reply.

Unfortunately, despite switching to `sqlalchemy_firebird` version 2.0.1, updating `SQLalchemy` to version 2.0.22 and when using either `fdb` 2.0.2 or `firebird-driver` 1.10.0, the problem still persists in the exact same manner - the exception that is given to `FBDialect.is_disconnect` is not one of the two expected types. This causes the error to bubble up instead of just being caught and the connection recycled.

Adding the line `print(f"sqlalchemy_firebird -- {e=} -- {type(e)=}")` at the beginning of the `is_disconnect` method reveals the type of the exception to be the following:
- when using fdb: `type(e)=<class 'fdb.fbcore.DatabaseError'>`
- when using firebird-driver: `type(e)=<class 'firebird.driver.types.DatabaseError'>`

Adding `self.dbapi.DatabaseError` to the types that are caught seems to fix the problem though.

**Comment by fdcastel** [comment]
Thank you @PracticallyNothing for this report.

#38 should fix this for both drivers now.

@pauldex please review and merge ASAP.
