### ISSUE TITLE
Support for descending indexes

### ISSUE THREAD

**Issue by gordthompson** [pauldex/sqlalchemy-firebird#6]
Firebird indexes are a bit different than most others in that they are all uni-directional. We would need to do some tweaking of `visit_create_index` to support this, as described in

https://github.com/sqlalchemy/sqlalchemy/issues/5106

That would be in addition to excluding the "noncol_idx" tests in ComponentReflectionTest.
- [ ] update visit_create_index to emit a valid CREATE DESC INDEX... statement for Firebird

**Comment by pauldex** [comment]
Should this issue be closed?

**Comment by gordthompson** [comment]
We can leave it open as a reminder that we still haven't done the `visit_create_index` part yet. That is, we've prevented the existing "DESC" tests from failing, but we are still unable to emit a `CREATE DESCENDING INDEX ...` statement.

**Comment by pauldex** [comment]
Sounds good.
